### ISSUE TITLE
Makefile.inc ?

### ISSUE THREAD

**Issue by FirasSadiyah** [maxplanck-ie/data_repository#1]
Hello, 

I am trying to generate the `data_repository` for a specific organism to run in SnakePipes (Develop). It seems to me that 'Makefile.inc' is missing. Would you please let me know how can I obtain this file or how to generate one myself? 

Many thanks.

**Comment by dpryan79** [comment]
You're looking for this then: https://github.com/maxplanck-ie/data_repository/blob/master/organisms/Makefile.inc

BTW, there's now a `createIndices` workflow in snakePipes. The version with that isn't available in conda yet, but I'll try to get things tagged and uploaded today. That should be much more convenient for you then using this repository :)

**Comment by dpryan79** [comment]
1.0.0 beta 1 of snakePipes with the `createIndices` workflow has now been tagged on github and is available on conda.

**Comment by FirasSadiyah** [comment]
Many thanks for your swift response. 

My bad, I kept only the makefile(s) for the relevant organisms in the `organisms` directory and moved the rest of them, including `Makefile.inc`!, into a separate one.

Perfect. I will use snakePipes with `createIndices` instead. Well done for such a useful workflow.
